apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: kubectl run mydep --image=alpine:latest --record=true --dry-run=true --output=yaml
  labels:
    run: mydep
  name: mydep
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mydep
  template:
    metadata:
      labels:
        run: mydep
    spec:
      containers:
        - image: alpine:latest
          name: mydep
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo 'Container is running'; sleep 3600; done"]
#alpine:3.17, 3.18, 3.19
