apiVersion: v1
kind: Pod
metadata:
  name: pod-env12
spec:
  containers:
  - name: env-var-configmap
    image: nginx:1.7.9
    env:
    - name: testenv
      valueFrom:
        configMapKeyRef:
          name: example-configmap
          key: database
