apiVersion: v1
kind: Pod
metadata:
  name: quota-mem-cpu-demo-2
  namespace: quotaz
spec:
  containers:
  - name: quota-mem-cpu-demo-2-ctr
    image: redis
    resources:
      limits:
        memory: "2Gi"
        cpu: "800m"
      requests:
        memory: "700Mi"
        cpu: "400m"
