apiVersion: v1
kind: Pod
metadata:
  name: staging-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - staging
  containers:
  - name: nginx
    image: nginx
